#name : throw Exception
# --
throw new ${1:Type}Exception($2);